/*
 *
 * userProfile constants
 *
 */

export const USER_PROFILE_REQUEST = 'PRO/USER_PROFILE_REQUEST';
export const USER_PROFILE_FAILURE = 'PRO/USER_PROFILE_FAILURE';
export const USER_PROFILE_SUCCESS = 'PRO/USER_PROFILE_SUCCESS';
export const USER_PROFILE_SHOULD_UPDATE = 'USER_PROFILE_SHOULD_UPDATE';
